### ISSUE TITLE
Does not work with pathogen

### ISSUE THREAD

**Issue by DelvarWorld** [Rykka/clickable.vim#7]
Really it would be nice if there weren't 3 separate projects to clone.

I have all three repos installed:

    .vim/bundle (master) $ ls os clickable clickable-things/
        clickable: ...
        clickable-things/: ...
        os: ...

But when I open a new vim instance with a new file in it and try to click on a link:

    [CLICK]  os#init is needed, please install bundle 'rykka/os.vim'
    Error detected while processing function <SNR>97_OnClick..259..273..clickable#util#browse:
    line   11:
    E121: Undefined variable: s:os
    E15: Invalid expression: s:os.is_mac
    line   17:
    E121: Undefined variable: cmd
    E15: Invalid expression: cmd
    line   18:
    E121: Undefined variable: cmd
    E116: Invalid arguments for function system

Also in the source of .vim/bundle/os/autoload/os.vim I don't see any reference to `s:os` but that may not be an actual issue?

**Comment by Rykka** [comment]
removed os requirement now,

**Comment by DelvarWorld** [comment]
looks good now!
